import streamkeycipher, secrets, mersenne,optimized_mersenne

print ("Testing of Problem 2")
print ("---------------------------------------------------------------------")
print("Part 1: A demonstration of the behavior of PRG, using the non-optimized version")
print("\n")
a = secrets.randbelow(2**32)
print("First, a seed of value less than 2^32")
mersenne.setSeed(a)
print("Printing 10 different pseudo random numbers")
for i in range(10):
    print("%d: %d" % (i,mersenne.nextInt()))
print("Another seed less than 2^32")
print("Printing 10 different pseudo random numbers, values should be different")
b = secrets.randbelow(10000)
mersenne.setSeed(b)
for i in range(10):
    print("%d: %d" % (i,mersenne.nextInt()))
print("Back to the original seed")
print("Printing 10 different pseudo random numbers, values should be the same as the first one")
mersenne.setSeed(a)
for i in range(10):
    print("%d: %d" % (i,mersenne.nextInt()))
print ("---------------------------------------------------------------------")
print("Part 2: A demonstration of the behavior of PRG, using the optimized version")
print("The behavior should be the same, using the same seed as the first part")
print("\n")
print("First, a seed of value less than 2^32")
optimized_mersenne.setSeed(a)
print("Printing 10 different pseudo random numbers")
for i in range(10):
    print("%d: %d" % (i,optimized_mersenne.nextInt()))
print("Another seed less than 2^32")
print("Printing 10 different pseudo random numbers, values should be different")
optimized_mersenne.setSeed(b)
for i in range(10):
    print("%d: %d" % (i,optimized_mersenne.nextInt()))
print("Back to the original seed")
print("Printing 10 different pseudo random numbers, values should be the same as the first one")
optimized_mersenne.setSeed(a)
for i in range(10):
    print("%d: %d" % (i,optimized_mersenne.nextInt()))

print ("---------------------------------------------------------------------")
print ("Part 3: Testing encrypting")
print ("Encrypting 'My name is Lam Ngo'")
encrypted_1 = streamkeycipher.encrypt(streamkeycipher.secret_key,streamkeycipher.iv,"My name is Lam Ngo", streamkeycipher.chars)
print(encrypted_1)

print("\n")
print ("Encrypting 'I am a student of Union College and I go to class early ever morning, so the Professor doesn't hate me'")
encrypted_2 = streamkeycipher.encrypt(streamkeycipher.secret_key,streamkeycipher.iv,"I am a student of Union College and I go to class early ever morning, so the Professor doesn't hate me", streamkeycipher.chars)
print(encrypted_2)

print("\n")
print ("Encrypting 'The Shape of Water'")
encrypted_3 = streamkeycipher.encrypt(streamkeycipher.secret_key,streamkeycipher.iv,"The Shape of Water", streamkeycipher.chars)
print(encrypted_3)
print("\n")
print ("---------------------------------------------------------------------")
print("Part 4: Testing decrypting")
print ("Decrypting 'My name is Lam Ngo' from above")
print (streamkeycipher.decrypt(streamkeycipher.secret_key,streamkeycipher.iv,encrypted_1, streamkeycipher.chars))

print("\n")
print ("Decrypting 'I am a student of Union College and I go to class early ever morning, so the Professor doesn't hate me' from above")
print (streamkeycipher.decrypt(streamkeycipher.secret_key,streamkeycipher.iv,encrypted_2, streamkeycipher.chars))

print("\n")
print ("Decrypting 'The Shape of Water' from above")
print (streamkeycipher.decrypt(streamkeycipher.secret_key,streamkeycipher.iv,encrypted_3, streamkeycipher.chars))
